Updated commit hook to prevent from adding excessive includes when de…
votca/dev-tools pull request #2
Opened 2019-01-26 20:05 UTC by JoshuaSBrown

…aling with boost, essentially will ignore suggested includes coming from boost.

Hey @JensWehner what do you think of this?

2019-01-26 22:02 UTC, JensWehner commented
I do not understand it. What does it do?

2019-01-29 21:19 UTC, JoshuaSBrown commented
1. It updates the license date to the current year, of every file you change
2. It calls include-what-you-use on every file you changed

* I have removed any includes that are automatically pulled in from boost, because include-what-you-use goes a little crazy with boost includes. 

3. It automatically calls clang-format on all the files you changed. 

You simply have to make the script executable and place it in the repo in .git/hooks with the file name pre-commit. 

Any time you call commit it will run.

2019-01-31 21:09 UTC, JensWehner commented
do you want to wait till you can set a environment variable?

2019-02-01 00:52 UTC, junghans requested changes

2019-02-01 00:52 UTC, junghans commented on pre-commit
> +  data=$(include-what-you-use $file 2>&1 )
```suggestion
if [[ ! ${DONT_USE_INCLUDE_WHAT_YOU_USE} ]]; then
    data=$(include-what-you-use $file 2>&1 )
 fi
```

2019-02-02 17:06 UTC, JoshuaSBrown commented
@junghans hey I fixed this.  Take a look.

2019-02-03 00:29 UTC, merged